name: Solar System App CICD Workflow

### Trigger on branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

### Environment variables from Github secrets/variables
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:

 ### Unit Testing and uploading the artifact with Matrix testing on different node.js version and OS 
  unit-testing:
    name: Unit Testing
    runs-on: ${{ matrix.operating_system }}
   
    strategy:
      matrix:
        nodejs_version: [18, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
            path: node_modules
            key: ${{runner.os}}-npm-${{hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        id: nodejs-unit-testing-step
        run: npm test

      - name: Archive Test Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}
          path: test-results.xml
          retention-days: 5

### Code-coverage and uploading the artifact
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

      
