name: Solar System App CICD Workflow

### Trigger the workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

### Environment Variables

env:
    MONGO_URI: ${{ vars.MONGO_URI }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:

### Unit Testing Section 

    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJs version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Check env presence
          run: |
            echo "MONGO_URI is set: ${{ env.MONGO_URI != '' }}"
            echo "MONGO_USERNAME is set: ${{ env.MONGO_USERNAME != '' }}"
            echo "MONGO_PASSWORD is set: ${{ env.MONGO_PASSWORD != '' }}"


        - name: Unit Testing
          run: npx mocha app-test.js --timeout 10000 --reporter spec --exit

        
